site_name: Cardeal
site_description: Repositório do Grupo 4 da disciplina Arquitetura e Desenho de Software
repo_url: https://github.com/UnBArqDsw2021-1/2021.1_G04_Cardeal

nav:
  - Home: index.md
  - Apresentações: apresentacoes.md
  - 1. Desenho de Sofware(Base):
    - 1.1 Módulo Projeto Não Orientado a Abordagem Específicas:
      - Design Sprint: desenhoSoftwareBase/designSprint.md
      - Protótipo: desenhoSoftwareBase/prototipo.md
      - Pŕe-rastreabilidade:
        - 5W2H: desenhoSoftwareBase/5W2H.md
        - Causa e efeito: desenhoSoftwareBase/causaEfeito.md
        - Rich Picture: desenhoSoftwareBase/richPicture.md
      - Elicitação de requisitos:
        - Storyboard: desenhoSoftwareBase/storyboard.md
        - Brainstorm: desenhoSoftwareBase/brainstorm.md
        - Léxico: desenhoSoftwareBase/lexico.md
        - Estimativas: desenhoSoftwareBase/estimativas.md
    - 1.2 Módulo Processos/Metodologias /Abordagens:
      - Metodologia: desenhoSoftwareBase/metodologia.md
      - Modelagem BPMN: desenhoSoftwareBase/modelagemBpmn.md
    - Extras:
      - Documento de Visão: desenhoSoftwareBase/documento-de-visao.md
      - Horários disponiveis: horarioGrupo/horarioGrupo.md
      - Política do Repositório:
        - Políticas de Branch: desenhoSoftwareBase/politicas/politicasBranch.md
        - Políticas de Issue: desenhoSoftwareBase/politicas/politicasIssue.md
        - Políticas de Pull Request: desenhoSoftwareBase/politicas/politicasPR.md
        - Políticas de Commit: desenhoSoftwareBase/politicas/politicasCommits.md
      - Atas:
        - 27/07/2021: Atas/27-07-2021.md
        - 30/07/2021: Atas/30-07-2021.md
        - 02/08/2021: Atas/02-08-2021.md
        - 04/08/2021: Atas/04-08-2021.md
        - 05/08/2021: Atas/05-08-2021.md
  - 2. Desenho de Software (Modelagem):
    - 2.1 Módulo Projeto Orientado a Abordagens Tradicionais:
        - 2.1.1 Notação UML – Diagramas Estáticos:
          - Diagrama de Classes: modelagem/diagrama_classes.md
        - 2.1.2 Notação UML – Diagramas Dinâmicos:
          - Apagar: modelagem/diagrama_classes.md
        - 2.1.3 Modelagem Ágil:
          - Apagar: modelagem/diagrama_classes.md
        - Extras:
          - Diagrama de Casos de Uso: modelagem/diagrama_casos_de_uso.md
          - Identidade visual: modelagem/identidadeVisual.md
          - Debate - Identidade visual: modelagem/debateIdentidadeVisual.md
          - Correções: modelagem/correcoes_E1.md
          - Atas:
            - 13/08/2021: Atas/13-08-2021.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  # language: pt
  # logo: assets/logo.png
  # features:
  #   - navigation.instant
  #   - navigation.tabs
  #   - navigation.top
  #   - navigation.tabs.sticky

  language: pt
  logo: assets/logo.png
  
  palette:
      scheme: slate
      primary: blue grey



  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    # - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png



extra:
  social:
    - type: "github"
      link: "https://github.com/UnBArqDsw2021-1/2021.1_G04_Cardeal"

plugins:
  - search
  - awesome-pages